server:
  port: 80
spring:
  application:
    name: crowd-member-gateway
  profiles:
    active: redis
zuul:
  ignored-services: "*"       # 表示忽视直接通过application-name访问微服务，必须通过route
  sensitive-headers:
  add-host-header: true
  routes:
    route_auth:
      service-id: crowd-member-auth
      path: /**
    route_project:
      service-id: crowd-member-service-project
      path: /project/**
      strip-prefix: false     # 默认转发时会删除前缀，这里设置 strip-prefix 即可

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka
    register-with-eureka: true
    fetch-registry: true
# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug

ignore:
  whites:
    - /
    - /auth/**
    - /**/*.css
    - /**/*.js
    - /**/fonts/**
    - /**/img/**
