spring:
  redis:
    host: 192.168.227.30
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  # 设置 SpringSession 使用 redis 进行统一存储
  session:
    store-type: redis