spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crowd_member?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    druid:
      initial-size: 5
      max-active: 10

# 修改 Mybatis Plus 日志输出等级
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启对于 xml 文件的 自动转驼峰配置
    map-underscore-to-camel-case: true
#    object-wrapper-factory: pers
  #    object-wrapper-factory: com.baomidou.mybatisplus.extension.MybatisMapWrapperFactory
  mapper-locations: classpath*:/pers/prover07/crowd/mysql/mapper/xml/*.xml
