server:
  port: 8001
spring:
  application:
    name: crowd-member-auth
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka
    register-with-eureka: true
    fetch-registry: true
