server:
  port: 8002
spring:
  application:
    name: crowd-member-service-project
  profiles:
    active: redis, mysql, rabbit
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka
    register-with-eureka: true
    fetch-registry: true
oss:
  client:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    bucketName: prover-member
    accessKeyId: LTAI5tByzqHLYumrUstmYSS4
    accessKeySecret: YA0HsprfrBiUQtUh5KblS8bcpR1Fsg

